version: '{build}'
image: Visual Studio 2019

environment:
  matrix:
  # Available python versions and their locations on https://www.appveyor.com/docs/build-environment/#python
  - PYTHON: C:\Python37-x64
    TOXENV: py37-default
  - PYTHON: C:\Python38-x64
    TOXENV: py38-default

build: off

install:
- cmd: SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
- cmd: pip install tox

before_test:
- cmd: python --version
- cmd: pip --version
- cmd: tox --version

test_script:
- cmd: tox
